#NumPy Notebook

In [1]:
!pip install numpy

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.1/5.1 MB 5.8 MB/s  0:00:00 eta 0:00:01


In [2]:
import numpy as np
np.set_printoptions(suppress=True)  # Keep outputs compact

def describe(name, arr):
    print(f"{name}: shape={arr.shape}, ndim={arr.ndim}, dtype={arr.dtype}\n{arr}\n")

## 1. Mental Model: Shapes, Vectorization, Broadcasting

In [3]:
# Shapes: 1D, 2D, 3D
vec = np.array([1, 2, 3])
mat = np.array([[1, 2, 3], [4, 5, 6]])
tensor = np.arange(8).reshape(2, 2, 2)

describe("1D vector", vec)
describe("2D matrix", mat)
describe("3D tensor", tensor)

1D vector: shape=(3,), ndim=1, dtype=int64
[1 2 3]

2D matrix: shape=(2, 3), ndim=2, dtype=int64
[[1 2 3]
 [4 5 6]]

3D tensor: shape=(2, 2, 2), ndim=3, dtype=int64
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]



In [4]:
# Vectorization vs Python loop
data = np.arange(5)
loop_result = []
for x in data:
    loop_result.append(x * 2)
vectorized_result = data * 2
print(f"Loop result    : {loop_result}")
print(f"Vectorized     : {vectorized_result.tolist()}")

Loop result    : [np.int64(0), np.int64(2), np.int64(4), np.int64(6), np.int64(8)]
Vectorized     : [0, 2, 4, 6, 8]


In [5]:
# Broadcasting examples
base = np.array([[10, 20, 30], [40, 50, 60]])
scalar_added = base + 5  # Scalar stretches to every element
row = np.array([1, 2, 3])
row_added = base + row  # Row vector stretches across rows

describe("Base", base)
print("Scalar broadcasting:\n", scalar_added, "\n", sep="")
print("Row broadcasting:\n", row_added, sep="")

Base: shape=(2, 3), ndim=2, dtype=int64
[[10 20 30]
 [40 50 60]]

Scalar broadcasting:
[[15 25 35]
 [45 55 65]]

Row broadcasting:
[[11 22 33]
 [41 52 63]]


## 2. Universal Syntax Patterns: Creation and Indexing

In [6]:
# Creation helpers
from_list = np.array([1, 2, 3])
zeros = np.zeros((3, 3))
ones = np.ones((2, 4))
arange_vals = np.arange(0, 10, 2)
linspace_vals = np.linspace(0, 1, 5)

print("From list      :", from_list)
print("Zeros (3x3)    :\n", zeros)
print("Ones (2x4)     :\n", ones)
print("arange(0,10,2) :", arange_vals)
print("linspace(0,1,5):", linspace_vals)

From list      : [1 2 3]
Zeros (3x3)    :
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones (2x4)     :
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
arange(0,10,2) : [0 2 4 6 8]
linspace(0,1,5): [0.   0.25 0.5  0.75 1.  ]


In [7]:
# Comma syntax indexing
arr = np.array([[10, 11, 12], [20, 21, 22], [30, 31, 32]])
single = arr[0, 1]          # Row 0, Col 1
slice_rows_cols = arr[0:2, 1:]  # Rows 0-1, Col 1 onward

print("arr:\n", arr)
print("arr[0,1]          =>", single)
print("arr[0:2,1:]\n", slice_rows_cols)

arr:
 [[10 11 12]
 [20 21 22]
 [30 31 32]]
arr[0,1]          => 11
arr[0:2,1:]
 [[11 12]
 [21 22]]


## 3. Essential Methods: Inspect, Aggregate, Reshape

In [8]:
# Inspect
inspect_arr = np.array([[1.0, 2.5], [3.5, 4.5]])
print("shape:", inspect_arr.shape)
print("dtype:", inspect_arr.dtype)
print("ndim :", inspect_arr.ndim)

shape: (2, 2)
dtype: float64
ndim : 2


In [9]:
# Aggregation with axis
agg = np.array([[1, 2, 3], [4, 5, 6]])
print("agg:\n", agg)
print("Sum all      =>", agg.sum())
print("Sum axis=0   =>", agg.sum(axis=0))  # collapse rows
print("Mean axis=1  =>", agg.mean(axis=1))
print("Max value    =>", agg.max())
print("Argmax index =>", agg.argmax())

agg:
 [[1 2 3]
 [4 5 6]]
Sum all      => 21
Sum axis=0   => [5 7 9]
Mean axis=1  => [2. 5.]
Max value    => 6
Argmax index => 5


In [10]:
# Reshape
reshaped = np.arange(6).reshape(2, 3)
describe("Reshaped 2x3", reshaped)

Reshaped 2x3: shape=(2, 3), ndim=2, dtype=int64
[[0 1 2]
 [3 4 5]]



## 4. Common Pitfalls: Views vs Copies, Shape Mismatch

In [11]:
# View vs copy
orig = np.array([1, 2, 3, 4])
view_slice = orig[1:3]      # view
view_slice[:] = 0           # modifies orig
copy_slice = orig[1:3].copy()
copy_slice[:] = 99          # does not modify orig

print("After view edit, orig =>", orig)
print("View slice            =>", view_slice)
print("Copy slice (indep.)   =>", copy_slice)

After view edit, orig => [1 0 0 4]
View slice            => [0 0]
Copy slice (indep.)   => [99 99]


In [12]:
# Shape mismatch example
a = np.zeros((3, 2))
b_ok = np.array([1, 2])
print("Broadcast works (3x2 + (2,)):\n", a + b_ok)

b_bad = np.array([1, 2, 3])
try:
    a + b_bad
except ValueError as exc:
    print("Broadcast fails (3x2 + (3,)) =>", exc)

Broadcast works (3x2 + (2,)):
 [[1. 2.]
 [1. 2.]
 [1. 2.]]
Broadcast fails (3x2 + (3,)) => operands could not be broadcast together with shapes (3,2) (3,) 
